name: checklinks

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install URL-checking script
        run: |
          pip install requests markdown beautifulsoup4
          wget https://raw.githubusercontent.com/yallop/check-markdown-urls/master/src/check_markdown_urls.py
      - name: check the URLs
        run: python check_markdown_urls.py README.md
